### ISSUE TITLE
Lines with no content (double-carriage-return) yield an error.

### ISSUE THREAD

**Issue by chr15m** [yardsale8/hymagic#1]
```
(print "Hello!")
```

yeilds "Hello!"

```
(print "Hi!")

(print "yes")
```

yeilds `IndexError: string index out of range`

Thanks for the fantastic plugin - I've had a lot of fun with this!

**Comment by yardsale8** [comment]
Glad you are enjoying the plugin.

Could you give me a few more details:
python ?
did you install hymagic from pip or the repo?  If github, which branch? (completion branch is a WIP)
Which ipython interface (terminal, gui, notebook)?

**Comment by chr15m** [comment]
Hello!

> python ?

`2.7.6-final`

> did you install hymagic from pip or the repo?

My `requirements.txt` says: `hymagic==0.1` so I think that means from pip.

> Which ipython interface (terminal, gui, notebook)? 

iPython/Jupyter notebook server 4.0.6.

Thanks for your time!

**Comment by yardsale8** [comment]
As I pointed out in the other issue, make sure you start all hylang cells with the `%%hylang` cell magic.  
The following works for me in the ipython notebook*:

```
In [1]: %load_ext hymagic

In [2]: %%hylang
        (print "Hi!")
        (print "Hello")

Hi!
Hello
```

Can you verify that this works for you as well?  If not, please provide the complete traceback.
- I have been having trouble getting a virtualenv up with your specific versions for python and ipython, but I did check this in python 2.7.11
