### ISSUE TITLE
Support Hy-native notebooks

### ISSUE THREAD

**Issue by chr15m** [yardsale8/hymagic#3]
Selecting 'New' -> 'Hy' to create a native Hy notebook causes errors #1 and #2. Running a Python notebook and using the magics does not cause these issues.

**Comment by yardsale8** [comment]
Ok, then I think your problem was with a different module (probably hy_kernel?).  This module only supplies the magic commands as a quick fix to getting hylang into IPython.

(Sorry for the LATE reply!)
